use worldwineweb;

INSERT INTO `stato` (`sigla`, `nome`) VALUES ('AFG', 'Afghanistan');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ALB', 'Albania');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('DZA', 'Algeria');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('AND', 'Andorra');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('AGO', 'Angola');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('AIA', 'Anguilla');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ATA', 'Antartide');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ATG', 'Antigua e Barbuda');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SAU', 'Arabia Saudita');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ARG', 'Argentina');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ARM', 'Armenia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ABW', 'Aruba');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('AUS', 'Australia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('AUT', 'Austria');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('AZE', 'Azerbaigian');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BHS', 'Bahamas');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BHR', 'Bahrein');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BGD', 'Bangladesh');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BRB', 'Barbados');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BEL', 'Belgio');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BLZ', 'Belize');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BEN', 'Benin');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BMU', 'Bermuda');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BTN', 'Bhutan');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BLR', 'Bielorussia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MMR', 'Birmania');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BOL', 'Bolivia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BIH', 'Bosnia ed Erzegovina');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BWA', 'Botswana');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BRA', 'Brasile');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BRN', 'Brunei');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BGR', 'Bulgaria');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BFA', 'Burkina Faso');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BDI', 'Burundi');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('KHM', 'Cambogia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CMR', 'Camerun');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CAN', 'Canada');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CPV', 'Capo Verde');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TCD', 'Ciad');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CHL', 'Cile');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CHN', 'Cina');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CYP', 'Cipro');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('VAT', 'Città del Vaticano');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('COL', 'Colombia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('COM', 'Comore');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('PRK', 'Corea del Nord');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('KOR', 'Corea del Sud');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CIV', 'Costa d''Avorio');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CRI', 'Costa Rica');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('HRV', 'Croazia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CUB', 'Cuba');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CUW', 'Curaçao');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('DNK', 'Danimarca');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('DMA', 'Dominica');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ECU', 'Ecuador');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('EGY', 'Egitto');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SLV', 'El Salvador');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ARE', 'Emirati Arabi Uniti');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ERI', 'Eritrea');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('EST', 'Estonia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ETH', 'Etiopia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('FJI', 'Figi');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('PHL', 'Filippine');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('FIN', 'Finlandia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('FRA', 'Francia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GAB', 'Gabon');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GMB', 'Gambia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GEO', 'Georgia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SGS', 'Georgia del Sud e Isole Sandwich Australi');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('DEU', 'Germania');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GHA', 'Ghana');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('JAM', 'Giamaica');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('JPN', 'Giappone');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GIB', 'Gibilterra');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('DJI', 'Gibuti');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('JOR', 'Giordania');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GRC', 'Grecia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GRD', 'Grenada');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GRL', 'Groenlandia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GLP', 'Guadalupa');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GUM', 'Guam');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GTM', 'Guatemala');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GGY', 'Guernsey');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GIN', 'Guinea');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GNB', 'Guinea-Bissau');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GNQ', 'Guinea Equatoriale');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GUY', 'Guyana');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GUF', 'Guyana francese');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('HTI', 'Haiti');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('HND', 'Honduras');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('HKG', 'Hong Kong');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('IND', 'India');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('IDN', 'Indonesia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('IRN', 'Iran');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('IRQ', 'Iraq');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('IRL', 'Irlanda');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ISL', 'Islanda');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BVT', 'Isola Bouvet');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('IMN', 'Isola di Man');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CXR', 'Isola di Natale');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('NFK', 'Isola Norfolk');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ALA', 'Isole Åland');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BES', 'Isole BES');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CYM', 'Isole Cayman');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CCK', 'Isole Cocos (Keeling)');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('COK', 'Isole Cook');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('FRO', 'Fær Øer');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('FLK', 'Isole Falkland');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('HMD', 'Isole Heard e McDonald');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MNP', 'Isole Marianne Settentrionali');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MHL', 'Isole Marshall');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('UMI', 'Isole minori esterne degli Stati Uniti');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('PCN', 'Isole Pitcairn');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SLB', 'Isole Salomone');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('VGB', 'Isole Vergini britanniche');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('VIR', 'Isole Vergini americane');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ISR', 'Israele');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ITA', 'Italia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('JEY', 'Jersey');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('KAZ', 'Kazakistan');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('KEN', 'Kenya');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('KGZ', 'Kirghizistan');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('KIR', 'Kiribati');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('KWT', 'Kuwait');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('LAO', 'Laos');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('LSO', 'Lesotho');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('LVA', 'Lettonia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('LBN', 'Libano');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('LBR', 'Liberia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('LBY', 'Libia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('LIE', 'Liechtenstein');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('LTU', 'Lituania');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('LUX', 'Lussemburgo');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MAC', 'Macao');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MKD', 'Macedonia del Nord');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MDG', 'Madagascar');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MWI', 'Malawi');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MYS', 'Malaysia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MDV', 'Maldive');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MLI', 'Mali');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MLT', 'Malta');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MAR', 'Marocco');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MTQ', 'Martinica');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MRT', 'Mauritania');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MUS', 'Mauritius');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MYT', 'Mayotte');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MEX', 'Messico');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('FSM', 'Micronesia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MDA', 'Moldavia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MNG', 'Mongolia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MNE', 'Montenegro');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MSR', 'Montserrat');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MOZ', 'Mozambico');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('NAM', 'Namibia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('NRU', 'Nauru');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('NPL', 'Nepal');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('NIC', 'Nicaragua');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('NER', 'Niger');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('NGA', 'Nigeria');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('NIU', 'Niue');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('NOR', 'Norvegia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('NCL', 'Nuova Caledonia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('NZL', 'Nuova Zelanda');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('OMN', 'Oman');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('NLD', 'Paesi Bassi');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('PAK', 'Pakistan');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('PLW', 'Palau');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('PSE', 'Palestina');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('PAN', 'Panama');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('PNG', 'Papua Nuova Guinea');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('PRY', 'Paraguay');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('PER', 'Perù');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('PYF', 'Polinesia francese');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('POL', 'Polonia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('PRI', 'Porto Rico');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('PRT', 'Portogallo');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MCO', 'Monaco');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('QAT', 'Qatar');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('GBR', 'Regno Unito');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('COD', 'RD del Congo');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CZE', 'Rep. Ceca');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CAF', 'Rep. Centrafricana');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('COG', 'Rep. del Congo');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('DOM', 'Rep. Dominicana');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('REU', 'Riunione');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ROU', 'Romania');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('RWA', 'Ruanda');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('RUS', 'Russia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ESH', 'Sahara Occidentale');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('KNA', 'Saint Kitts e Nevis');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('LCA', 'Saint Lucia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SHN', 'Sant''Elena, Ascensione e Tristan da Cunha');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('VCT', 'Saint Vincent e Grenadine');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('BLM', 'Saint-Barthélemy');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('MAF', 'Saint-Martin');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SPM', 'Saint-Pierre e Miquelon');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('WSM', 'Samoa');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ASM', 'Samoa Americane');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SMR', 'San Marino');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('STP', 'São Tomé e Príncipe');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SEN', 'Senegal');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SRB', 'Serbia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SYC', 'Seychelles');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SLE', 'Sierra Leone');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SGP', 'Singapore');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SXM', 'Sint Maarten');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SYR', 'Siria');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SVK', 'Slovacchia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SVN', 'Slovenia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SOM', 'Somalia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ESP', 'Spagna');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('LKA', 'Sri Lanka');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('USA', 'Stati Uniti');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ZAF', 'Sudafrica');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SDN', 'Sudan');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SSD', 'Sudan del Sud');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SUR', 'Suriname');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SJM', 'Svalbard e Jan Mayen');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SWE', 'Svezia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('CHE', 'Svizzera');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('SWZ', 'Swaziland');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TWN', 'Taiwan');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TJK', 'Tagikistan');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TZA', 'Tanzania');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ATF', 'Terre australi e antartiche francesi');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('IOT', 'Territorio britannico dell''Oceano Indiano');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('THA', 'Thailandia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TLS', 'Timor Est');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TGO', 'Togo');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TKL', 'Tokelau');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TON', 'Tonga');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TTO', 'Trinidad e Tobago');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TUN', 'Tunisia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TUR', 'Turchia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TKM', 'Turkmenistan');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TCA', 'Turks e Caicos');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('TUV', 'Tuvalu');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('UKR', 'Ucraina');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('UGA', 'Uganda');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('HUN', 'Ungheria');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('URY', 'Uruguay');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('UZB', 'Uzbekistan');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('VUT', 'Vanuatu');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('VEN', 'Venezuela');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('VNM', 'Vietnam');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('WLF', 'Wallis e Futuna');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('YEM', 'Yemen');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ZMB', 'Zambia');
INSERT INTO `stato` (`sigla`, `nome`) VALUES ('ZWE', 'Zimbabwe');


INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '0.375', 'mezza bottiglia');
INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '0.750', 'standard');
INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '1.500', 'magnum');
INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '3.000', 'jeroboam');
INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '4.500', 'rehoboam');
INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '6.000', 'mathusalem');
INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '9.000', 'salmanazar');
INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '12.00', 'balthazar');
INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '15.00', 'nabuchodonosor');
INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '18.00', 'melchior');
INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '20.00', 'salomon');
INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '25.00', 'sovereign');
INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '27.00', 'goliath');
INSERT INTO `contenitore` (`idContenitore` , `capacita`, `tipologia`) VALUES (NULL, '30.00', 'melchizedec');


INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Aglianico');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Aglianicone');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Albana Nera');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Aleatico');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Alicante');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Ancelotta');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Barbera');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', "Barbera dell'Emilia");
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Bombino nero');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Bonarda');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Bovale sardo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Brachetto');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Cabernet franc');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Cabernet-Sauvignon');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Caddiu');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Cagnulari');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Calabrese');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Canaiolo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Canina');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Cannonau');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Carignano');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Casetta');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Castiglione');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Centesimino');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Cesanese');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Ciliegiolo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Clinton');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Colorino');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Corvina');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Corvinone');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Croatina');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Dolcetto');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Enantio');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Fortana');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Fragolino');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Franconia');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Frappato');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Freisa');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Fumin');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Gaglioppo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Gamay');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Grappello Ruberti');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Greco nero');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Grignolino');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Groppello');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Lacrima');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Lagrein');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Lambrusco');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Longanesi');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Magliocco canino');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Malvasia di Casorzo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Malvasia di Schierano');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Malvasia nera di Brindisi');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Malvasia nera di Lecce');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Mammolo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Marzemino');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Merlot');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Molinara');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Monica');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Montepulciano');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Moscato di Scanzo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Moscato rosa');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Nebbiolo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Negrara');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Negrettino');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Negroamaro');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Nerello');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Nerello mascalese');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Nero Buono');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', "Nero d'Avola");
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Neyret');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Nieddera');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Nocera');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Notardomenico');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Ottavianello');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Perricone');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Pignolo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Pinot nero');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Primitivo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Prugnolo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Raboso');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Rebo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Refosco dal peduncolo rosso');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Rondinella');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Rossese');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Rossignola');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Ruchè');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Sagrantino');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Sangiovese');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Schiava');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Schioppettino');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Sciascinoso');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Susumaniello');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Syrah');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Teroldego');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Terrano del Carso Triestino');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Tintilia');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Tocai rosso');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Traminer aromatico');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Uva di Troia');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Uva Longanesi');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Uva rara');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Vernaccia');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Vespolina');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Nera', 'Vin de Nus');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Albana');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Ansonica');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Antiniello');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Arneis');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Arvisionadu');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Asprinio');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Baratuciat');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Bellone');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Biancame');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Bianchello');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Biancolella');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Bombino bianco');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Bosco');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Bovale grande');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Carricante');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Catarratto');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Chardonnay');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Chasselas');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Cividino');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Cococciola');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Coda di Volpe');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Cortese');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Durello');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Erbaluce');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Falanghina');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Fiano');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Forastera');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Francavidda');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Friulano');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Garganega');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Glera (prosecco)');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Grecanico dorato');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Grechetto');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Greco');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Greco bianco');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Grillo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Guarnaccia');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Impigno');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Inzolia');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Kerner');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Lumassina');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Malvasia');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Marchione');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Maruggio');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Minutolo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Montonico');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Montù');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Moscato');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Moscatello selvatico');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Müller-Thurgau');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Nasco');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Nosiola');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Nuragus');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Ortrugo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Pampanuto');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Passerina');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Pecorino');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Pepella');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Picolit');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Pigato');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Pignoletto');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Pinot bianco');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Pinot grigio');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Prié blanc');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Prosecco');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Ramandolo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Ribolla gialla');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Riesling');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Sauvignon');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Sylvaner Veltiner');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Torbato');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Traminer aromatico');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Trebbiano');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Verdeca');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Verdicchio');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Verduzzo');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Vermentino');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Vernaccia');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Viognier');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Vitovska');
INSERT INTO `vitigno` (`idVitigno`, `coloreBacca`, `nomeSpecie`) VALUES (NULL, 'Chiara', 'Zibibbo');


INSERT INTO `cantina` (`idCantina`, `nome`, `stato`) VALUES (NULL, 'Menestrello', 'ITA');
INSERT INTO `cantina` (`idCantina`, `nome`, `stato`) VALUES (NULL, 'Ca’ del Bosco', 'ITA');
INSERT INTO `cantina` (`idCantina`, `nome`, `stato`) VALUES (NULL, 'Umani Ronchi', 'ITA');
INSERT INTO `cantina` (`idCantina`, `nome`, `stato`) VALUES (NULL, 'Mionetto', 'ITA');
INSERT INTO `cantina` (`idCantina`, `nome`, `stato`) VALUES (NULL, 'Villa Bonaga', 'ITA');
INSERT INTO `cantina` (`idCantina`, `nome`, `stato`) VALUES (NULL, 'Casa Sant''Orsola', 'ITA');
INSERT INTO `cantina` (`idCantina`, `nome`, `stato`) VALUES (NULL, 'Terre Forti', 'ITA');
INSERT INTO `cantina` (`idCantina`, `nome`, `stato`) VALUES (NULL, 'Santa Barbara', 'ITA');
INSERT INTO `cantina` (`idCantina`, `nome`, `stato`) VALUES (NULL, 'Tenuta Coccapane', 'ITA');
INSERT INTO `cantina` (`idCantina`, `nome`, `stato`) VALUES (NULL, 'Chablis Vititours', 'FRA');
INSERT INTO `cantina` (`idCantina`, `nome`, `stato`) VALUES (NULL, 'La Bodega Tinedo', 'ESP');


INSERT INTO `menzione` (`idMenzione`, `menzione`) VALUES (NULL, 'Passito');
INSERT INTO `menzione` (`idMenzione`, `menzione`) VALUES (NULL, 'Passito Liquoroso');
INSERT INTO `menzione` (`idMenzione`, `menzione`) VALUES (NULL, 'Riserva');
INSERT INTO `menzione` (`idMenzione`, `menzione`) VALUES (NULL, 'Riserva Superiore');
INSERT INTO `menzione` (`idMenzione`, `menzione`) VALUES (NULL, 'Novello');
INSERT INTO `menzione` (`idMenzione`, `menzione`) VALUES (NULL, 'Gran Selezione');
INSERT INTO `menzione` (`idMenzione`, `menzione`) VALUES (NULL, 'Superiore');

INSERT INTO `utente` (`idUtente`, `email`, `password`, `ruolo`, `nome`, `cognome`, `dataDiNascita`, `cf`, `partitaIva`, `ragioneSociale`, `attivo`) VALUES
(1, 'ma.giacchini99@gmail.com', 'a123', 'admin', 'Mattia', 'Giacchini', '1999-05-11', 'GCCMTT99E11H199O', NULL, NULL, 1),
(2, 'dejackdani@gmail.com', '123456aA', 'admin', 'Daniele', 'Ercoles', '1992-10-19', 'RCLDNL92R19C357C', NULL, NULL, 1),
(3, 'a@b.it', 'a123', 'client', 'Grandi', 'Filomeno', '1991-01-20', 'GRNFMN02T04A944S', NULL, NULL, 1);
